name: www actions
run-name: ${{ github.actor }} is now running
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on:
      steps:
        - name: builder
          uses: Hoppermq/ci-kitchenette/astro/build@master
